### ISSUE TITLE
Add support for sk-ssh-ed25519 keys

### ISSUE THREAD

**Issue by PorkCharsui79** [puppetlabs/puppetlabs-accounts#409]
## Solution
In the file **[accounts/lib/puppet/functions/accounts_ssh_authorized_keys_line_parser.rb](https://github.com/puppetlabs/puppetlabs-accounts/blob/064cb6464b1c7cac3d1578b24aecee6beff97a85/lib/puppet/functions/accounts_ssh_authorized_keys_line_parser.rb#L19)** change the following line:
`matched = str.match(%r{((sk-ecdsa-|ssh-|ecdsa-)[^\s]+)\s+([^\s]+)\s+(.*)$})`
to:
`matched = str.match(%r{((sk-ssh-ed25519|sk-ecdsa-|ssh-|ecdsa-)[^\s]+)\s+([^\s]+)\s+(.*)$})`

## Alternative
Why have this check in the first place? If I want to shoot myself in the foot, let me.

**Comment by bastelfreak** [comment]
Hi, thanks for bringing this up. Could you submit a patch for this?

**Comment by PorkCharsui79** [comment]
will do.. thx!
