### ISSUE TITLE
locked => true not working?

### ISSUE THREAD

**Issue by nem8** [puppetlabs/puppetlabs-accounts#416]
## Describe the Bug
Setting parameter locked to true does not change default shell for user

## Expected Behavior
According to the documentation, setting locked => true should set the user shell to something invalid, it does not..

## Steps to Reproduce
Create a user with the Accounts module
Set the user to locked
Verify shell set in /etc/passwd

## Environment
Puppet: 6.28.0
Accounts: 7.2.0

## Additional Context
Initially i wanted to remove the user accounts, but i could not find a way to do this (no ensure => absent parameter), is this even possible?
Then i went with locking the accounts, but this does not change the shell, and thus does nothing as far as i can tell?

**Comment by saz** [comment]
I've tried to reproduce this issue, but it's working for me. @nem8 are you sure, that you've set `locked => true` properly?

To remove a user, you just need to set `ensure => 'absent'`:
```
accounts::user { 'some-user':
  ensure => 'absent',
}
```
See https://github.com/puppetlabs/puppetlabs-accounts/blob/main/manifests/user.pp#L232

**Comment by nem8** [comment]
I did try setting the user accounts to absent as well without any change.
It seems there might be something else going on in my environment which requires some more debugging, I will look into it.
