### ISSUE TITLE
Remove "managehome" hard coded value when deleting a user

### ISSUE THREAD

**Issue by CoreyCook8** [puppetlabs/puppetlabs-accounts#438]
## Use Case
When deleting a user in puppet, this [workaround](https://github.com/puppetlabs/puppetlabs-accounts/blob/3cedba7affa33d92a2cffad3a06c5db4d1dfd139/manifests/user.pp#L237) causes this [line](https://github.com/puppetlabs/puppet/blob/9d98dbfb788990692221b8ad0008db7d84be2502/lib/puppet/provider/user/useradd.rb#L353) to never resolve to true, preventing the -r flag from being added to the userdel cmd. While `purge_user_home` exists to delete the user's home directory, this leaves the user's mail spool in the /var/spool/mail directory which would otherwise be deleted if you could set `managehome` to true.

## Describe the Solution You Would Like
Being that the referenced issue is resolved, I would like to have the option to set `managehome` to true so that the users mail spool is not left hanging.

## Describe Alternatives You've Considered
I was able to achieve the same result but setting sshkey_custom_path equal to the mail spool path but this is not a long term solution.

**Comment by jordanbreen28** [comment]
Thanks for your work with this @CoreyCook8.
Fixed in your PR https://github.com/puppetlabs/puppetlabs-accounts/pull/439

**Comment by CoreyCook8** [comment]
Thank you @jordanbreen28! I was wondering if there was any way to make a 7.3.2 release with this fix in it? I didn't realize I had some puppet 6 dependencies preventing me from going to 8+. If not, then no worries, I will get to >8.0 soon!

Thanks again for your help!
