### ISSUE TITLE
Max Password Age should support a value of negative one to set "Password never expires" on Linux

### ISSUE THREAD

**Issue by bschonec** [puppetlabs/puppetlabs-accounts#465]
## Use Case
'change -M -1 <user>' sets the password to never expire on Linux

## Describe the Solution You Would Like
Currently, the $password_max_age doesn't allow a value of negative one on any platform.  On Linux at least, setting the 'chage -M' parameter to negative zero will disable password expiry.

#466

**Comment by sirinek** [comment]
The funny thing is that this uses the underlying user type, which DOES support -1.  
I sent this very issue into Puppet support several years ago and I recall them fixing it, I think this is a regression from pe_accounts.

**Comment by bschonec** [comment]
Resolved by #466
