### ISSUE TITLE
Is accounts::group broken?

### ISSUE THREAD

**Issue by sysadmiral** [puppetlabs/puppetlabs-accounts#50]
I'm still learning my way around puppet so forgive me if this is not really an issue but is the accounts::group class mentioned in the example files broken because it is not defined anywhere?

Please tell me this is the case because I have been banging my head against a wall trying to get this working!

:cry:

**Comment by emrtldrgn** [comment]
Are you going to submit a PR for this?

**Comment by tphoney** [comment]
Puppet does not normally issues page on github projects. The issues section will be closed, i have created an appropriate ticket here https://tickets.puppetlabs.com/browse/MODULES-5217  in our backlog apologies for the inconvenience.
