### ISSUE TITLE
Will the purge_sshkeys code be pushed to puppetforge anytime soon?

### ISSUE THREAD

**Issue by kindred** [puppetlabs/puppetlabs-accounts#52]

**Comment by kindred** [comment]
Any information on this? I'm looking to use this feature, but the puppetforge version doesn't contain it.

**Comment by skrysmanski** [comment]
Seems to be on puppetforge now.

**Comment by tphoney** [comment]
Puppet does not normally use the issues page on github projects. The issues section will be closed, i have created an appropriate ticket here https://tickets.puppetlabs.com/browse/MODULES-5218 in our backlog apologies for the inconvenience.

**Comment by tphoney** [comment]
Version 1.1.0 released Sep 20th 2016
