### ISSUE TITLE
Allow users to specify the primary group

### ISSUE THREAD

**Issue by micah-uber** [puppetlabs/puppetlabs-accounts#61]
Currently you force the user to have a primary group of the users name. It would be nice to be able to specify the user's primary group instead.

Similar to https://github.com/deric/puppet-accounts/issues/12

**Comment by tphoney** [comment]
It looks like this functionality was merged with #85 . If you still have an issue can you create a ticket at https://tickets.puppetlabs.com/browse/MODULES
