### ISSUE TITLE
managehome option not fully implemented. 

### ISSUE THREAD

**Issue by Kanbyen** [puppetlabs/puppetlabs-accounts#67]
It appears that managehome = false does not do anything other then tell the module to not manage .ssh dirs.

I would expect this to tell it to ignore all defaults/settings for managed home directories.   Is this something that was planned this way or not fully implemented? 

thanks

**Comment by tphoney** [comment]
Puppet does not normally use the issues page on github projects. The issues section will be closed, i have created an appropriate ticket here https://tickets.puppetlabs.com/browse/MODULES-5221 in our backlog, apologies for the inconvenience.
