### ISSUE TITLE
$home/.vim directory conflict

### ISSUE THREAD

**Issue by uder** [puppetlabs/puppetlabs-accounts#73]
If $managehome==true, then module does much helpful things like manges .bashrc and ssh keys. It's really helpful.
But also it creates $home/.vim directory, and this resource declaration conflicts with modules? that manages vim. For example: 'ghoneycutt-vim'
As far as I can see, your module doesn't manages any vim configurations, so maybe you can remove $home/.vim declaration, or add another hiera variable (managevim for example) to disable this? I would be really appreciated.

**Comment by tphoney** [comment]
Puppet does not normally use the issues page on github projects. The issues section will be closed, i have created an appropriate ticket here https://tickets.puppetlabs.com/browse/MODULES-5222 in our backlog apologies for the inconvenience.
