### ISSUE TITLE
Failure if $create_group is set to false

### ISSUE THREAD

**Issue by ayush12030** [puppetlabs/puppetlabs-accounts#88]
If $create_group is set to false, puppet run fails with the following error:
`Could not find resource 'Group[username]' for relationship on 'User[username]`

This is because in Line 123
` if $ensure == 'present' {
    Group[$name] -> User[$name]
  }`

Here even if you have $create_group=false, it will try to establish a relationship between the group and user.

Similarly, line 139
`require              => [ User[$name], Group[$name] ],`

Here the group resource is required even if $create_group=false

**Comment by tphoney** [comment]
Hi @ayush12030 could you look at creating a PR for this branch with your change. We are closing the issues section for accounts, if you want to raise anything you can do it here https://tickets.puppetlabs.com/browse/MODULES
