### ISSUE TITLE
Wrong number format: validate_re(): input needs to be a String, not a Fixnum

### ISSUE THREAD

**Issue by khaefeli** [puppetlabs/puppetlabs-accounts#91]
When I submit a $uid and $gid value (from hiera) over create_resource() to the `accounts/manifests/user.pp` I get the following error:
` validate_re(): input needs to be a String, not a Fixnum`

fix:
`    validate_re($uid, '^\d+$')`
change to:
`    validate_re("$uid", '^\d+$')`

**Comment by tphoney** [comment]
Hi @khaefeli could you please look at creating a PR for this. Many thanks for finding the solution, if you have any further issue you can create an issue @ https://tickets.puppetlabs.com/browse/MODULES 

Thanks again.
